name: Cron job

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Cron job running every minute"
